Frontend:
  impl: LoadStoreTrace
  path: /home/ic/JXTF/HBM/research/hbm-modeling/traces/seq_rd.trace
  clock_ratio: 8

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: HBM3
    org:
      channel_width: 64
      preset: HBM3_2Gb
    timing:
      preset: HBM3_2Gbps

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy

  AddrMapper:
    impl: ChRaBaRoCo