static const char cov_style[] =
":root {\n"
"    --table-row-color: #e8e8e8;\n"
"    --margin-left: 20%;\n"
"}\n"
"\n"
"body {\n"
"    background-color: #f0f0e0ff;\n"
"}\n"
"\n"
"header {\n"
"    padding: 0.5em;\n"
"    text-align: center;\n"
"    font-size: 14pt;\n"
"}\n"
"\n"
"h1 {\n"
"    text-align: center;\n"
"}\n"
"\n"
"h2 {\n"
"    word-wrap: break-word;\n"
"}\n"
"\n"
"h3 {\n"
"    word-wrap: break-word;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"hr {\n"
"    border:none;\n"
"    height: 2px;\n"
"    background: black;\n"
"}\n"
"\n"
"footer {\n"
"    display: table;\n"
"    text-align: center;\n"
"    margin-left: auto;\n"
"    margin-right: auto;\n"
"}\n"
"\n"
"nav {\n"
"    float: left;\n"
"    background-color: var(--table-row-color);\n"
"    width: 17%;\n"
"    overflow: auto;\n"
"    padding: 10px;\n"
"    margin-top: -2px;\n"
"    border: 2px solid black;\n"
"}\n"
"nav details details {\n"
"    margin-left: 1rem;\n"
"}\n"
"nav details > a {\n"
"    padding-left: 1.9rem;\n"
"    display: block;\n"
"}\n"
"nav summary {\n"
"    display: inline-flex;\n"
"    cursor: pointer;\n"
"    align-items: center;\n"
"}\n"
"nav summary::before {\n"
"    content: '▶';\n"
"    font-size: 0.7em;\n"
"    margin-right: 0.4em;\n"
"}\n"
"nav details[open] > summary::before {\n"
"    transform: rotate(90deg);\n"
"}\n"
"\n"
"table {\n"
"    table-layout: fixed;\n"
"}\n"
"\n"
"table, th, td {\n"
"    border: 2px solid black;\n"
"    border-collapse: collapse;\n"
"    word-wrap: break-word;\n"
"}\n"
"\n"
".tabcontent {\n"
"    display: none;\n"
"    padding: 0px 0px;\n"
"    border: 2px solid #ccc;\n"
"    border-top: none;\n"
"    word-wrap: break-word;\n"
"}\n"
"\n"
".tab {\n"
"    overflow: hidden;\n"
"    border: 2px solid;\n"
"    margin-left: var(--margin-left);\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
".cbg:hover {\n"
"    background-color: #dddddd;\n"
"}\n"
".cbg {\n"
"    background-color: #bbbbbb;\n"
"    text-align: center;\n"
"}\n"
"\n"
".cbt {\n"
"    margin-top: 8px;\n"
"}\n"
".cbt th {\n"
"    background-color: #bbbbbb;\n"
"    text-align: center;\n"
"}\n"
".cbt td, .cbt th {\n"
"    width: 50px;\n"
"    text-align: center;\n"
"}\n"
".cbt td + td, .cbt th + th {\n"
"    width: 150px;\n"
"}\n"
".cbt td + td + td, .cbt th + th + th {\n"
"    width: 150px;\n"
"}\n"
".cbt td + td + td + td, .cbt th + th + th + th {\n"
"    width: 150px;\n"
"}\n"
"\n"
".percent100 {\n"
"    background-color: #00cc00;\n"
"}\n"
".percent90 {\n"
"    background-color: #e6e600;\n"
"}\n"
".percent80 {\n"
"    background-color: #ff9900;\n"
"}\n"
".percent0 {\n"
"    background-color: #ff0000;\n"
"}\n"
".percentna {\n"
"    background-color: #cccccc;\n"
"}\n"
"\n"
".nav-sel {\n"
"    font-weight: bold;\n"
"}\n"
;
